### ISSUE TITLE
Compiled app not found.

### ISSUE THREAD

**Issue by dreirund** [alexander-fischer/DVB-Verspaetungen#2]
The app seems no longer be in the google play store. `README.md` points to [https://play.google.com/store/apps/details?id=eu.alexanderfischer.dvbverspaetungsinfo&hl=de](https://play.google.com/store/apps/details?id=eu.alexanderfischer.dvbverspaetungsinfo&hl=de), where I only get an error 404 not found.

Can the app be made available google-free, e.g. `.apk` file for direct download, and included in the google play store?

Regards!

**Comment by alexander-fischer** [comment]
@felixbecker2 it was removed from play store quite a time ago, mostly because of using of an old way of handling background tasks directly on the phone. Feel free to checkout the project and compile it yourself :)
